**1) Install/ Import the required Python Packages/ Libraries**

In [1]:
#Import required python packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Ridge
import warnings
warnings.filterwarnings("ignore")
from sklearn import preprocessing
%matplotlib inline

In [2]:
pip install category_encoders

Requirement already satisfied: category_encoders in c:\users\lkant\anaconda3\lib\site-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in c:\users\lkant\appdata\roaming\python\python311\site-packages (from category_encoders) (1.25.2)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\lkant\anaconda3\lib\site-packages (from category_encoders) (1.3.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\lkant\anaconda3\lib\site-packages (from category_encoders) (1.11.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\lkant\anaconda3\lib\site-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in c:\users\lkant\appdata\roaming\python\python311\site-packages (from category_encoders) (2.1.1)
Requirement already satisfied: patsy>=0.5.1 in c:\users\lkant\anaconda3\lib\site-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lkant\appdata\roaming\python\python311\site-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\lkant\appdata\roaming\python\python311\site-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\lkant\appdata\roaming\python\python311\site-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in c:\users\lkant\appdata\roaming\python\python311\site-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\lkant\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\lkant\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\lkant\appdata\roaming\python\python311\site-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Note: you may need to restart the kernel to use updated packages.

**2) Mounting the Google Drive**

In [3]:
# Mount the Google Drive
# from google.colab import drive
# drive.mount('/content/gdrive')

**3) Read the Data file and check**

In [4]:
# Read the Diabetes Data from .csv file and check the data shape (number of Rows and Columns)
train_df = pd.read_csv('C:/Users/lkant/Documents/05_Streamlit_Bigmart_Sales/Data-Files/Bigmart_sales_train1.csv')
print(train_df.shape)
train_df.head()

(2637, 12)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDY07,11.80,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266
3,FDX32,15.10,Regular,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,Medium,Tier 1,Supermarket Type1,1589.2646
4,FDP49,9.00,Regular,0.069196,Breakfast,54.3614,OUT049,1999,Medium,Tier 1,Supermarket Type1,718.3982

In [5]:
# Read the Diabetes Data from .csv file and check the data shape (number of Rows and Columns)
test_df = pd.read_csv('C:/Users/lkant/Documents/05_Streamlit_Bigmart_Sales/Data-Files/Bigmart_sales_customer1.csv')
print(test_df.shape)
test_df.head()

(500, 11)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
3,FDN33,6.305,Regular,0.123365,Snack Foods,95.7436,OUT045,2002,NaN,Tier 2,Supermarket Type1
4,FDT44,16.600,Low Fat,0.103569,Fruits and Vegetables,118.3466,OUT017,2007,NaN,Tier 2,Supermarket Type1

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2637 entries, 0 to 2636
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            2637 non-null   object
 1   Item_Weight                2637 non-null   float64
 2   Item_Fat_Content           2637 non-null   object
 3   Item_Visibility            2637 non-null   float64
 4   Item_Type                  2637 non-null   object
 5   Item_MRP                   2637 non-null   float64
 6   Outlet_Identifier          2637 non-null   object
 7   Outlet_Establishment_Year  2637 non-null   int64
 8   Outlet_Size                1587 non-null   object
 9   Outlet_Location_Type       2637 non-null   object
 10  Outlet_Type                2637 non-null   object
 11  Item_Outlet_Sales          2637 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 247.3+ KB

In [7]:
train_df.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1050
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [8]:
train_df.fillna(train_df.mode().iloc[0], inplace=True)

In [9]:
train_df.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [10]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            500 non-null    object
 1   Item_Weight                500 non-null    float64
 2   Item_Fat_Content           500 non-null    object
 3   Item_Visibility            500 non-null    float64
 4   Item_Type                  500 non-null    object
 5   Item_MRP                   500 non-null    float64
 6   Outlet_Identifier          500 non-null    object
 7   Outlet_Establishment_Year  500 non-null    int64
 8   Outlet_Size                294 non-null    object
 9   Outlet_Location_Type       500 non-null    object
 10  Outlet_Type                500 non-null    object
dtypes: float64(3), int64(1), object(7)
memory usage: 43.1+ KB

In [11]:
test_df.isnull().sum()

Item_Identifier                0
Item_Weight                    0
Item_Fat_Content               0
Item_Visibility                0
Item_Type                      0
Item_MRP                       0
Outlet_Identifier              0
Outlet_Establishment_Year      0
Outlet_Size                  206
Outlet_Location_Type           0
Outlet_Type                    0
dtype: int64

In [12]:
test_df.fillna(test_df.mode().iloc[0], inplace=True)

In [13]:
test_df.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

In [14]:
train_df['train']=1
test_df['test'] = 0

In [15]:
combined_df  = pd.concat([train_df, test_df])
combined_df.shape

(3137, 14)

In [16]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3137 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            3137 non-null   object
 1   Item_Weight                3137 non-null   float64
 2   Item_Fat_Content           3137 non-null   object
 3   Item_Visibility            3137 non-null   float64
 4   Item_Type                  3137 non-null   object
 5   Item_MRP                   3137 non-null   float64
 6   Outlet_Identifier          3137 non-null   object
 7   Outlet_Establishment_Year  3137 non-null   int64
 8   Outlet_Size                3137 non-null   object
 9   Outlet_Location_Type       3137 non-null   object
 10  Outlet_Type                3137 non-null   object
 11  Item_Outlet_Sales          2637 non-null   float64
 12  train                      2637 non-null   float64
 13  test                       500 non-null    float64
dtypes: float64(6), int64(1), object(7)
memory usage: 367.6+ KB

###**Column-1: Item_Identifier**

In [17]:
combined_df['Item_Identifier'].value_counts()

Item_Identifier
FDA15    5
FDV33    5
FDT09    5
FDR21    5
FDT44    5
        ..
FDA14    1
FDZ50    1
FDO11    1
FDR57    1
NCF06    1
Name: count, Length: 880, dtype: int64

**Observations:**
* a) Data in this column will not be contributing to the prediction of the Depenedent variable

**Decsion:**

**We will be dropping this column**

**Action:**

In [18]:
combined_df.drop(['Item_Identifier'], axis = 1, inplace = True)
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3137 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Weight                3137 non-null   float64
 1   Item_Fat_Content           3137 non-null   object
 2   Item_Visibility            3137 non-null   float64
 3   Item_Type                  3137 non-null   object
 4   Item_MRP                   3137 non-null   float64
 5   Outlet_Identifier          3137 non-null   object
 6   Outlet_Establishment_Year  3137 non-null   int64
 7   Outlet_Size                3137 non-null   object
 8   Outlet_Location_Type       3137 non-null   object
 9   Outlet_Type                3137 non-null   object
 10  Item_Outlet_Sales          2637 non-null   float64
 11  train                      2637 non-null   float64
 12  test                       500 non-null    float64
dtypes: float64(6), int64(1), object(6)
memory usage: 343.1+ KB

###**Column-2: Item_Weight**

In [19]:
combined_df['Item_Weight'].value_counts()

Item_Weight
17.600    38
16.000    34
9.600     33
13.150    33
18.250    32
          ..
6.460      1
8.000      1
14.750     1
17.200     1
5.675      1
Name: count, Length: 311, dtype: int64

**Observations:**
* a) Data in this column is of "float" datatype. 

**Decsion:**

**So, we will keep this column as it is.**

###**Column-3: Item_Fat_Content**

In [20]:
combined_df['Item_Fat_Content'].value_counts()

Item_Fat_Content
Low Fat    1942
Regular     982
LF          123
reg          48
low fat      42
Name: count, dtype: int64

**Observations:**
* a) Data in this column is of "Object" or "String" datatype. The labels are of ordinal type. So we need to use label encoder. 
* b) Also, the data levels need to be modified like "low fat" and "LF" to "Low Fat", "reg" to "Regular".

**Decision:**
**We will be converting the data (after correcting the wrong labels) in this column into Numerical values using Ordnial Type method "preprocessing.LabelEncoder()**

**Observations:**
* a) Data in this column is of "Object" or "String" datatype. Also, the data levels are "Nominal" Type.

**Decsion:**

**We will be converting the data in this column into Numerical values using Nominal Type method "pd.get_dummies".**

In [21]:
combined_df.replace("LF", "Low Fat", inplace=True)
combined_df.replace("low fat", "Low Fat", inplace=True)
combined_df.replace("reg", "Regular", inplace=True)
combined_df['Item_Fat_Content'].value_counts()

Item_Fat_Content
Low Fat    2107
Regular    1030
Name: count, dtype: int64

In [22]:
le = preprocessing.LabelEncoder()
combined_df['Item_Fat_Content'] = le.fit_transform(combined_df.Item_Fat_Content.values)
combined_df['Item_Fat_Content'].value_counts()

Item_Fat_Content
0    2107
1    1030
Name: count, dtype: int64

In [23]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3137 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Weight                3137 non-null   float64
 1   Item_Fat_Content           3137 non-null   int32
 2   Item_Visibility            3137 non-null   float64
 3   Item_Type                  3137 non-null   object
 4   Item_MRP                   3137 non-null   float64
 5   Outlet_Identifier          3137 non-null   object
 6   Outlet_Establishment_Year  3137 non-null   int64
 7   Outlet_Size                3137 non-null   object
 8   Outlet_Location_Type       3137 non-null   object
 9   Outlet_Type                3137 non-null   object
 10  Item_Outlet_Sales          2637 non-null   float64
 11  train                      2637 non-null   float64
 12  test                       500 non-null    float64
dtypes: float64(6), int32(1), int64(1), object(5)
memory usage: 330.9+ KB

###**Column-4: Item_Visibility**

In [24]:
combined_df['Item_Visibility'].value_counts()

Item_Visibility
0.000000    189
0.076975      3
0.093766      2
0.107224      2
0.034868      2
           ...
0.142394      1
0.053976      1
0.031071      1
0.037616      1
0.047987      1
Name: count, Length: 2899, dtype: int64

**Observations:**
* a) Data in this column is of "float" datatype. Also, there seems to be no wrong data or wrong data format.

**Decsion:**

**Let us leave the column as it is.**

###**Column-5: Item_Type**

In [25]:
combined_df['Item_Type'].value_counts()

Item_Type
Snack Foods              796
Fruits and Vegetables    789
Household                597
Dairy                    440
Soft Drinks              287
Breads                   161
Breakfast                 67
Name: count, dtype: int64

**Observations:**
* a) Data in this column is of "Object" or "String" datatype. Also, the data levels are "Nominal" Type.

**Decsion:**

**We will be converting the data in this column into Numerical values using Nominal Type method "Binary Encoding" as we want to have minimum number of columns.**

In [26]:
le = preprocessing.LabelEncoder()
combined_df['Item_Type'] = le.fit_transform(combined_df.Item_Type.values)
combined_df['Item_Type'].value_counts()

Item_Type
5    796
3    789
4    597
2    440
6    287
0    161
1     67
Name: count, dtype: int64

In [27]:
combined_df['Item_MRP'].value_counts()

Item_MRP
196.5768    6
142.0154    5
139.9838    4
89.4856     4
160.9578    4
           ..
104.5964    1
164.9526    1
258.3304    1
157.4262    1
186.8898    1
Name: count, Length: 2697, dtype: int64

###**Column-6: Outlet_Identifier**

In [28]:
combined_df['Outlet_Identifier'].value_counts()

Outlet_Identifier
OUT049    634
OUT045    634
OUT035    625
OUT018    622
OUT017    622
Name: count, dtype: int64

**Observations:**
* a) Data in this column is of "Object" or "String" datatype. Also, the data levels are "Nominal" Type.

**Decision:**

**We will be converting the data in this column into Numerical values using Nominal Type method "Binary Encoding" as we want to have minimum number of columns.**

In [29]:
le = preprocessing.LabelEncoder()
combined_df['Outlet_Identifier'] = le.fit_transform(combined_df.Outlet_Identifier.values)
combined_df['Outlet_Identifier'].value_counts()

Outlet_Identifier
4    634
3    634
2    625
1    622
0    622
Name: count, dtype: int64

###**Column-7: Outlet_Establishment_Year**

In [30]:
combined_df['Outlet_Establishment_Year'].value_counts()

Outlet_Establishment_Year
1999    634
2002    634
2004    625
2009    622
2007    622
Name: count, dtype: int64

**Observations:**
* a) Data in this column is of "int" datatype. Also, there seems to be no wrong data or wrong data format.

**Decsion:**

**Let us leave the column as it is.**

###**Column-8: Outlet_Size**

In [31]:
combined_df['Outlet_Size'].value_counts()

Outlet_Size
Medium    2512
Small      625
Name: count, dtype: int64

**Observations:**
* a) Data in this column is of "Object" or "String" datatype. Also, the data levels are "Ordinal" Type.

**Decsion:**

**We will be converting the data in this column into Numerical values using Ordnial Type method "preprocessing.LabelEncoder()**

In [32]:
le = preprocessing.LabelEncoder()
combined_df['Outlet_Size'] = le.fit_transform(combined_df.Outlet_Size.values)
combined_df['Outlet_Size'].value_counts()

Outlet_Size
0    2512
1     625
Name: count, dtype: int64

###**Column-9: Outlet_Location_Type**

In [33]:
combined_df['Outlet_Location_Type'].value_counts()

Outlet_Location_Type
Tier 2    1881
Tier 1     634
Tier 3     622
Name: count, dtype: int64

**Observations:**
* a) Data in this column is of "Object" or "String" datatype. Also, the data levels are "Ordinal" Type.

**Decsion:**

**We will be converting the data in this column into Numerical values using Ordnial Type method "preprocessing.LabelEncoder()**

In [34]:
le = preprocessing.LabelEncoder()
combined_df['Outlet_Location_Type'] = le.fit_transform(combined_df.Outlet_Location_Type.values)
combined_df['Outlet_Location_Type'].value_counts()

Outlet_Location_Type
1    1881
0     634
2     622
Name: count, dtype: int64

###**Column-10: Outlet_Type**

In [35]:
combined_df['Outlet_Type'].value_counts()

Outlet_Type
Supermarket Type1    2515
Supermarket Type2     622
Name: count, dtype: int64

**Observations:**
* a) Data in this column is of "Object" or "String" datatype. Also, the data levels are "Ordinal" Type.

**Decsion:**

**We will be converting the data in this column into Numerical values using Ordnial Type method "preprocessing.LabelEncoder()**

In [36]:
le = preprocessing.LabelEncoder()
combined_df['Outlet_Type'] = le.fit_transform(combined_df.Outlet_Type.values)
combined_df['Outlet_Type'].value_counts()

Outlet_Type
0    2515
1     622
Name: count, dtype: int64

###**Column-11: Item_Outlet_Sales**

In [37]:
combined_df['Item_Outlet_Sales'].value_counts()

Item_Outlet_Sales
703.0848     10
1230.3984     9
1406.1696     7
1342.2528     7
1701.7848     6
             ..
1705.1138     1
3709.8376     1
3761.7700     1
2137.2180     1
7182.6504     1
Name: count, Length: 1710, dtype: int64

**Observations:**
* a) Data in this column is of "float" datatype. Also, there seems to be no wrong data or wrong data format.

**Decsion:**

**Let us leave the column as it is.**

In [38]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3137 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Weight                3137 non-null   float64
 1   Item_Fat_Content           3137 non-null   int32
 2   Item_Visibility            3137 non-null   float64
 3   Item_Type                  3137 non-null   int32
 4   Item_MRP                   3137 non-null   float64
 5   Outlet_Identifier          3137 non-null   int32
 6   Outlet_Establishment_Year  3137 non-null   int64
 7   Outlet_Size                3137 non-null   int32
 8   Outlet_Location_Type       3137 non-null   int32
 9   Outlet_Type                3137 non-null   int32
 10  Item_Outlet_Sales          2637 non-null   float64
 11  train                      2637 non-null   float64
 12  test                       500 non-null    float64
dtypes: float64(6), int32(6), int64(1)
memory usage: 269.6 KB

In [39]:
train_df1 = combined_df[combined_df["train"] == 1]
test_df1 = combined_df[combined_df["test"] == 0]
train_df1.drop(["train", "test"], axis=1, inplace=True)
test_df1.drop(["test", "train", "Item_Outlet_Sales"], axis=1, inplace=True)

In [40]:
train_df1.shape

(2637, 11)

In [41]:
test_df1.shape

(500, 10)

In [42]:
X = train_df1.drop(['Item_Outlet_Sales'], axis = 1)
y = train_df1['Item_Outlet_Sales']

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 66)

In [44]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(2109, 10)
(2109,)
(528, 10)
(528,)

In [45]:
X_train.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
1041,14.15,0,0.036147,6,39.3138,0,2007,0,1,0
1070,8.93,0,0.000000,4,53.2614,4,1999,0,0,0
452,11.50,0,0.000000,5,119.5124,1,2009,0,2,1
429,17.75,0,0.014577,3,160.7262,2,2004,1,1,0
562,15.60,1,0.105276,5,173.2764,2,2004,1,1,0

In [46]:
from sklearn.ensemble import RandomForestRegressor
RFR = RandomForestRegressor(n_estimators=300, random_state=0)
RFR.fit(X_train, y_train)

RandomForestRegressor(n_estimators=300, random_state=0)

In [47]:
# Calculate the accuracy of learning by the Algorithm
RFR.score(X_train,y_train)

0.9127941113676885

In [48]:
# Predicting the Test set results
RFR_y_pred = RFR.predict(X_test)

In [49]:
RFR_Training_Acc = RFR.score(X_train,y_train)
RFR_Testing_Acc = r2_score(y_test,RFR_y_pred)

In [50]:
print("Training Accuracy :", RFR_Training_Acc)
print("Testing Accuracy :", RFR_Testing_Acc)

Training Accuracy : 0.9127941113676885
Testing Accuracy : 0.3481316767028909

In [51]:
# Predicting the Test set results
RFR_test_pred = RFR.predict(test_df1)

In [52]:
# Read the Diabetes Data from .csv file and check the data shape (number of Rows and Columns)
cust_df = pd.read_csv('C:/Users/lkant/Documents/05_Streamlit_Bigmart_Sales/Data-Files/Bigmart_sales_customer1.csv')
print(cust_df.shape)
cust_df.head()

(500, 11)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
3,FDN33,6.305,Regular,0.123365,Snack Foods,95.7436,OUT045,2002,NaN,Tier 2,Supermarket Type1
4,FDT44,16.600,Low Fat,0.103569,Fruits and Vegetables,118.3466,OUT017,2007,NaN,Tier 2,Supermarket Type1

In [53]:
cust_df["Predicted_Sales_Value"]=RFR_test_pred

In [54]:
finalDF= cust_df
#finalDF['Predicted_Sales_Value'] = finalDF['Predicted_Sales_Value'].astype(int)
print(finalDF.shape)
finalDF.head()

(500, 12)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Predicted_Sales_Value
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1,1903.298047
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1,1213.245173
2,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1,2345.941861
3,FDN33,6.305,Regular,0.123365,Snack Foods,95.7436,OUT045,2002,NaN,Tier 2,Supermarket Type1,1079.248484
4,FDT44,16.600,Low Fat,0.103569,Fruits and Vegetables,118.3466,OUT017,2007,NaN,Tier 2,Supermarket Type1,1938.012859

In [55]:
finalDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            500 non-null    object
 1   Item_Weight                500 non-null    float64
 2   Item_Fat_Content           500 non-null    object
 3   Item_Visibility            500 non-null    float64
 4   Item_Type                  500 non-null    object
 5   Item_MRP                   500 non-null    float64
 6   Outlet_Identifier          500 non-null    object
 7   Outlet_Establishment_Year  500 non-null    int64
 8   Outlet_Size                294 non-null    object
 9   Outlet_Location_Type       500 non-null    object
 10  Outlet_Type                500 non-null    object
 11  Predicted_Sales_Value      500 non-null    float64
dtypes: float64(4), int64(1), object(7)
memory usage: 47.0+ KB

In [56]:
#from google.colab import files
finalDF.to_csv("C:/Users/lkant/Documents/05_Streamlit_Bigmart_Sales/Data-Files/Bigmart_sales_with_predicted_values2.csv", index = False)

In [57]:
import pickle
#now you can save it to a file
file = 'C:/Users/lkant/Documents/05_Streamlit_Bigmart_Sales/Data-Files/ML_Model_Bigmart_Sales.pkl'
with open(file, 'wb') as f:
    pickle.dump(RFR, f)

In [58]:
with open(file, 'rb') as f:
    k = pickle.load(f)

In [59]:
#cy=k.predict([[1,	22,	0,	2,	3,	15]])
cy=k.predict([[14.15,	0,	0.36147,	6,	39.3138, 0, 2007, 0, 1,	0]])
print(cy)

[531.53921067]